print("-----STUDENT DETAILS-----")
NAME =input("Enter your name:")
print("")
AGE =input("Enter your  age:")
print("")
USN =input("Enter your name:")
print("")
COURSE =input("Enter course:")
print("")
ADDRESS =input("Enter your address:")
print("")
COLLEGE_ADDRESS =input("Enter your college address:")
print("")
